### ISSUE TITLE
Add an option to not count single line or expression boidied methods 

### ISSUE THREAD

**Issue by xperiandri** [priyanshu92/AsyncMethodNameFixer#1]
Sometimes it is more efficient to pass through a `Task` returned from called method right away.

``` C#
async Task SomeMethodAsync(object a, object b, object c) {}

Task SomeMethodWithLessParametersAsync(object a, object b)
 => SomeMethodAsync(a, b, new object());
```

Like this.

Could you add an option to exclude this case from warning?

**Comment by priyanshu92** [comment]
Currently, it gives a warning to remove `Async` from `SomeMethodWithLessParametersAsync`. Do you want an option to disable that warning?
