### ISSUE TITLE
Add support for IAsyncEnumerable

### ISSUE THREAD

**Issue by gkathire** [priyanshu92/AsyncMethodNameFixer#12]
### Installed product versions
- Visual Studio: 2019 Professional
- This extension: 2.0.0

### Description
Functions that return IAsyncEnumerable are not identified as Async functions.

### Steps to recreate
1. Create a .net core 3 app and add the following function in the Program.cs and watch

public IAsyncEnumerable<string> GetStringAsync() { return null;}

### Current behavior
Function that returns IAsyncEnumerable as not identified as Async.

### Expected behavior
Function that returns IAsyncEnumerable as should be identified as Async.

**Comment by AdamWillden** [comment]
Just ran into this one and suspect this is going to become more prevalent as people switch over to C# 8.0

I see it probably just needs a fix in this function to indicate, when the method return type is `IAsyncEnumerable`, it should be considered awaitable: https://github.com/priyanshu92/AsyncMethodNameFixer/blob/22a2b2671650aeb8c1c2278dcedd1ef1556b6fbc/AsyncMethodNameFixer/AsyncMethodNameFixer/AsyncMethodNameFixerAnalyzer.cs#L38

**Comment by priyanshu92** [comment]
Will it be possible for you to send a PR for this one? I am a little busy with some stuff, might take some time for me to fix it.

**Comment by AdamWillden** [comment]
@priyanshu92 no problem. I am in the same boat at the moment (lots going on at work keeping my busy) but this may bug me enough to get around to it in due course.

**Comment by AdamWillden** [comment]
Oh and I've forgotten to thank you for this extension, its existence and your hard work is much appreciated. I feel sometimes this gets overlooked and I like to say thanks :-)

**Comment by priyanshu92** [comment]
This should be fixed in [v2.0.2](https://marketplace.visualstudio.com/items?itemName=PRIYANSHUAGRAWAL92.AsyncMethodNameFixer&ssr=false#overview)

**Comment by AdamWillden** [comment]
Wholehearted thank you @priyanshu92

Sorry I couldn't get around to it myself, work has been manic bouncing from release to release between two products. Thanks again.

**Comment by priyanshu92** [comment]
No problem 😄. Stay safe 🏠.
