### ISSUE TITLE
Do not mark overriding members as requiring Async suffix

### ISSUE THREAD

**Issue by Floyddotnet** [priyanshu92/AsyncMethodNameFixer#7]
### Installed product versions
- Visual Studio: [example 2017 Enterprise]
- This extension: [example 1.1.5]

### Description
Overriden members should be ignored.

### Current behavior / Example
`protected override async Task<IdentityResult> UpdatePasswordHash(...)`

produce warning: AMNF0001

**Comment by priyanshu92** [comment]
Fixed. Please update the extension to 2.0.0 or directly download from [here](https://marketplace.visualstudio.com/items?itemName=PRIYANSHUAGRAWAL92.AsyncMethodNameFixer)
